name: drlnd-p1-navigation
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _pytorch_select=0.2=gpu_0
  - attrs=19.1.0=py36_1
  - blas=1.0=mkl
  - ca-certificates=2019.5.15=1
  - certifi=2019.6.16=py36_1
  - cffi=1.12.3=py36h2e261b9_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.0=cuda10.0_0
  - decorator=4.4.0=py36_1
  - gmp=6.1.2=h6c8ec71_1
  - intel-openmp=2019.4=243
  - ipykernel=5.1.2=py36h39e3cac_0
  - ipython=7.8.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.5.1=py_0
  - jedi=0.15.1=py36_0
  - jinja2=2.10.1=py36_0
  - jsonschema=3.0.2=py36_0
  - jupyter_client=5.3.1=py_0
  - jupyter_core=4.5.0=py_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - markupsafe=1.1.1=py36h7b6447c_0
  - mistune=0.8.4=py36h7b6447c_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.0.14=py36ha843d7b_0
  - mkl_random=1.0.2=py36hd81dba3_0
  - nbformat=4.4.0=py36_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py36hfd86e86_0
  - notebook=6.0.1=py36_0
  - numpy=1.16.5=py36h7e9f1db_0
  - numpy-base=1.16.5=py36hde5b4d6_0
  - openssl=1.1.1d=h7b6447c_1
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.5.1=py_0
  - pexpect=4.7.0=py36_0
  - pip=19.2.2=py36_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.9=py36_0
  - pycparser=2.19=py36_0
  - pygments=2.4.2=py_0
  - python=3.6.9=h265db76_0
  - python-dateutil=2.8.0=py36_0
  - pytorch=1.2.0=cuda100py36h938c94c_0
  - readline=7.0=h7b6447c_5
  - setuptools=41.0.1=py36_0
  - sqlite=3.29.0=h7b6447c_0
  - testpath=0.4.2=py36_0
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.3=py36h7b6447c_0
  - traitlets=4.3.2=py36_0
  - webencodings=0.5.1=py36_1
  - wheel=0.33.4=py36_0
  - widgetsnbextension=3.5.1=py36_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.3.1=he6710b0_3
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.8.0
    - astor==0.8.0
    - atomicwrites==1.3.0
    - backcall==0.1.0
    - bleach==1.5.0
    - cloudpickle==1.2.2
    - cycler==0.10.0
    - defusedxml==0.6.0
    - docopt==0.6.2
    - entrypoints==0.3
    - gast==0.3.2
    - grpcio==1.11.0
    - h5py==2.10.0
    - html5lib==0.9999999
    - importlib-metadata==0.22
    - ipython-genutils==0.2.0
    - jupyter==1.0.0
    - jupyter-client==5.3.2
    - jupyter-console==6.0.0
    - kiwisolver==1.1.0
    - markdown==3.1.1
    - matplotlib==3.1.1
    - more-itertools==7.2.0
    - nbconvert==5.6.0
    - pickleshare==0.7.5
    - pillow==5.4.1
    - pluggy==0.13.0
    - protobuf==3.5.2
    - ptyprocess==0.6.0
    - py==1.8.0
    - pyparsing==2.4.2
    - pyrsistent==0.15.4
    - pytest==3.10.1
    - pyyaml==5.1.2
    - pyzmq==18.1.0
    - qtconsole==4.5.5
    - send2trash==1.5.0
    - six==1.12.0
    - tensorboard==1.7.0
    - tensorflow==1.7.1
    - termcolor==1.1.0
    - terminado==0.8.2
    - unityagents==0.4.0
    - wcwidth==0.1.7
    - werkzeug==0.15.6
    - zipp==0.6.0
prefix: /home/silvio/anaconda3/envs/drlnd-unity3d

